version: '3.7'

services:
  db:
    container_name: yamdb_db
    image: postgres:12.4
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    ports:
      - "5433:5433"
    env_file:
      - ./.env

  web:
    container_name: yamdb_web
    image: contrigra/api_yamdb:latest
    restart: always
    volumes:
      - static_volume:/code/static
    depends_on:
      - db
    env_file:
      - ./.env

  nginx:
    image: nginx:1.19.4
    container_name: yamdb_nginx
    restart: always
    volumes:
      - ./nginx/default.conf:/etc/nginx/conf.d/default.conf
      - static_volume:/code/static
    ports:
      - '80:80'
    depends_on:
      - web
volumes:
  postgres_data:
  static_volume: